#!/usr/bin/bash

if [ -z "$1" ] ; then
    echo $0 CMD
    exit 2
fi

set -x

mkdir -p $HOME/xdg
chmod -R 0700 $HOME/xdg
cd $HOME

xvfb-run -f xauth --auto-servernum -s "-screen 0 1024x768x24" dbus-launch --exit-with-x11 "$@"

