#!/usr/bin/bash

if [ -z "$1" ] ; then
    echo $0 CMD
    exit 2
fi

set -x

export HOME=/tmp/xvfb
mkdir -p $HOME/xdg
chmod -R 0700 $HOME
cd $HOME

(sleep 2 && x11vnc -display :100 -auth xauth -forever -nopw -quiet -listen 0.0.0.0) &
NO_AT_BRIDGE=1 SHELL=/bin/bash XDG_RUNTIME_DIR=xdg xvfb-run -n 100 -f xauth -s "-screen 0 1024x768x24" dbus-launch --exit-with-x11 "$@"

