#!/usr/bin/bash

if [ -z "$1" ] ; then
    echo $0 CMD
    exit 2
fi

set -x

export HOME=/xvfb
mkdir -p $HOME/xdg
chmod -R 0700 $HOME/xdg
cd $HOME

export NO_AT_BRIDGE=1
export SHELL=/bin/bash 
export XDG_RUNTIME_DIR=xdg

(sleep 1 && x11vnc -display :100 -auth xauth -forever -nopw -quiet -listen 0.0.0.0) &
xvfb-run -n 100 -f xauth -s "-screen 0 1024x768x24" dbus-launch --exit-with-x11 "$@"

